### ISSUE TITLE
peers asking for chain blocks much older than they should be

### ISSUE THREAD

**Issue by refacktor** [skepticoin/skepticoin#79] opened 2021-06-14 05:29 UTC
I made some minor tweaks in 17becaa936a2ec3b1e30bf5bb2b9a3d1b441d13f  to log additional information to try to understand what's going on in the peering code.

I'm a bit puzzled by what I see when running skepticoin-mine in my dev box:
```
2021-06-13 22:11:28,722  24.194.193.244 ConnectedRemotePeer.handle_receive_data()
2021-06-13 22:11:28,722  24.194.193.244 ConnectedRemotePeer.handle_message_received(GetBlocksMessage ts: 2021-06-13T22:11:28-07:00, id: 0000000391, req: 0000000358, ctx: 04851183329314688477)
2021-06-13 22:11:28,722  24.194.193.244 ConnectedRemotePeer.handle_get_blocks_message_received()
2021-06-13 22:11:28,722  24.194.193.244 requested start_height=5501
2021-06-13 22:11:28,726  24.194.193.244 ConnectedRemotePeer.send_message(InventoryMessage ts: 2021-06-13T22:11:28-07:00, id: 0000000392, req: 0000000391, ctx: 04851183329314688477)
2021-06-13 22:11:28,726  24.194.193.244 ConnectedRemotePeer.handle_message_received(GetBlocksMessage ts: 2021-06-13T22:11:28-07:00, id: 0000000392, req: 0000000359, ctx: 00995223359101531800)
2021-06-13 22:11:28,726  24.194.193.244 ConnectedRemotePeer.handle_get_blocks_message_received()
2021-06-13 22:11:28,726  24.194.193.244 requested start_height=5501
2021-06-13 22:11:28,730  24.194.193.244 ConnectedRemotePeer.send_message(InventoryMessage ts: 2021-06-13T22:11:28-07:00, id: 0000000393, req: 0000000392, ctx: 00995223359101531800)
2021-06-13 22:11:28,730  24.194.193.244 ConnectedRemotePeer.handle_message_received(GetBlocksMessage ts: 2021-06-13T22:11:29-07:00, id: 0000000393, req: 0000000360, ctx: 02047474701233890861)
2021-06-13 22:11:28,730  24.194.193.244 ConnectedRemotePeer.handle_get_blocks_message_received()
2021-06-13 22:11:28,730  24.194.193.244 requested start_height=5501
2021-06-13 22:11:28,733  24.194.193.244 ConnectedRemotePeer.send_message(InventoryMessage ts: 2021-06-13T22:11:28-07:00, id: 0000000394, req: 0000000393, ctx: 02047474701233890861)
2021-06-13 22:11:28,733  76.120.103.103 ConnectedRemotePeer.handle_receive_data()
2021-06-13 22:11:28,733  76.120.103.103 ConnectedRemotePeer.handle_message_received(DataMessage ts: 2021-06-13T22:11:28-07:00, id: 0000000331, req: 0000000331, ctx: 12149979815989269001)
2021-06-13 22:11:28,733  76.120.103.103 ConnectedRemotePeer.handle_data_message_received(type=b'\x00\x00' format=ts: 2021-06-13T22:11:28-07:00, id: 0000000331, req: 0000000331, ctx: 12149979815989269001)
2021-06-13 22:11:28,733  76.120.103.103 ConnectedRemotePeer.send_message(GetDataMessage ts: 2021-06-13T22:11:28-07:00, id: 0000000333, req: 0000000004, ctx: 12149979815989269001)
2021-06-13 22:11:28,733 ConnectedRemotePeer.handle_can_send()
2021-06-13 22:11:28,734 ConnectedRemotePeer.handle_can_send()
2021-06-13 22:11:28,734 ConnectedRemotePeer.handle_can_send()
2021-06-13 22:11:28,734  18.216.200.111 ConnectedRemotePeer.handle_receive_data()
2021-06-13 22:11:28,734  18.216.200.111 ConnectedRemotePeer.handle_message_received(GetBlocksMessage ts: 2021-06-13T22:11:29-07:00, id: 0000000135, req: 0000000133, ctx: 15855233366762512724)
2021-06-13 22:11:28,734  18.216.200.111 ConnectedRemotePeer.handle_get_blocks_message_received()
2021-06-13 22:11:28,734  18.216.200.111 requested start_height=24501
2021-06-13 22:11:28,738  18.216.200.111 ConnectedRemotePeer.send_message(InventoryMessage ts: 2021-06-13T22:11:28-07:00, id: 0000000136, req: 0000000135, ctx: 15855233366762512724)
2021-06-13 22:11:28,738  18.216.200.111 ConnectedRemotePeer.handle_message_received(GetBlocksMessage ts: 2021-06-13T22:11:29-07:00, id: 0000000136, req: 0000000134, ctx: 08814615144814270758)
2021-06-13 22:11:28,738  18.216.200.111 ConnectedRemotePeer.handle_get_blocks_message_received()
2021-06-13 22:11:28,738  18.216.200.111 requested start_height=24001
2021-06-13 22:11:28,742  18.216.200.111 ConnectedRemotePeer.send_message(InventoryMessage ts: 2021-06-13T22:11:28-07:00, id: 0000000137, req: 0000000136, ctx: 08814615144814270758)
2021-06-13 22:11:28,742 ConnectedRemotePeer.handle_can_send()
2021-06-13 22:11:28,742 ConnectedRemotePeer.handle_can_send()
2021-06-13 22:11:28,743 ConnectedRemotePeer.handle_can_send()
2021-06-13 22:11:28,743 ConnectedRemotePeer.handle_can_send()
2021-06-13 22:11:28,784  24.194.193.244 ConnectedRemotePeer.handle_receive_data()
2021-06-13 22:11:28,785  24.194.193.244 ConnectedRemotePeer.handle_message_received(GetBlocksMessage ts: 2021-06-13T22:11:29-07:00, id: 0000000394, req: 0000000361, ctx: 02439528416246808220)
2021-06-13 22:11:28,785  24.194.193.244 ConnectedRemotePeer.handle_get_blocks_message_received()
2021-06-13 22:11:28,785  24.194.193.244 requested start_height=5501
2021-06-13 22:11:28,800  24.194.193.244 ConnectedRemotePeer.send_message(InventoryMessage ts: 2021-06-13T22:11:28-07:00, id: 0000000395, req: 0000000394, ctx: 02439528416246808220)
2021-06-13 22:11:28,801 ConnectedRemotePeer.handle_can_send()
2021-06-13 22:11:28,815  18.216.200.111 ConnectedRemotePeer.handle_receive_data()
2021-06-13 22:11:28,815  18.216.200.111 ConnectedRemotePeer.handle_message_received(DataMessage ts: 2021-06-13T22:11:29-07:00, id: 0000000137, req: 0000000135, ctx: 00692073296723342280)
2021-06-13 22:11:28,816  18.216.200.111 ConnectedRemotePeer.handle_data_message_received(type=b'\x00\x00' format=ts: 2021-06-13T22:11:29-07:00, id: 0000000137, req: 0000000135, ctx: 00692073296723342280)
2021-06-13 22:11:28,979                 ChainManager.set_coinstate(CoinState @ 00011e56c6c73fa786a14905c1af3de55242efd4a7e1b7491c4c83e66a088b27 (h. 73008) w/ 1 heads)
2021-06-13 22:11:28,984  18.216.200.111 ConnectedRemotePeer.send_message(GetDataMessage ts: 2021-06-13T22:11:28-07:00, id: 0000000138, req: 0000000035, ctx: 00692073296723342280)
2021-06-13 22:11:28,985  24.194.193.244 ConnectedRemotePeer.handle_receive_data()
2021-06-13 22:11:28,985  24.194.193.244 ConnectedRemotePeer.handle_message_received(GetBlocksMessage ts: 2021-06-13T22:11:29-07:00, id: 0000000395, req: 0000000362, ctx: 13424551546170771246)
2021-06-13 22:11:28,985  24.194.193.244 ConnectedRemotePeer.handle_get_blocks_message_received()
2021-06-13 22:11:28,985  24.194.193.244 requested start_height=5501
2021-06-13 22:11:28,988  24.194.193.244 ConnectedRemotePeer.send_message(InventoryMessage ts: 2021-06-13T22:11:28-07:00, id: 0000000396, req: 0000000395, ctx: 13424551546170771246)
2021-06-13 22:11:28,988  18.216.200.111 ConnectedRemotePeer.handle_receive_data()
2021-06-13 22:11:28,988  18.216.200.111 ConnectedRemotePeer.handle_message_received(GetBlocksMessage ts: 2021-06-13T22:11:29-07:00, id: 0000000138, req: 0000000136, ctx: 15855233366762512724)
2021-06-13 22:11:28,989  18.216.200.111 ConnectedRemotePeer.handle_get_blocks_message_received()
2021-06-13 22:11:28,989  18.216.200.111 requested start_height=25001
2021-06-13 22:11:28,992  18.216.200.111 ConnectedRemotePeer.send_message(InventoryMessage ts: 2021-06-13T22:11:28-07:00, id: 0000000139, req: 0000000138, ctx: 15855233366762512724)
2021-06-13 22:11:28,992 ConnectedRemotePeer.handle_can_send()
2021-06-13 22:11:28,993 ConnectedRemotePeer.handle_can_send()
2021-06-13 22:11:28,993 ConnectedRemotePeer.handle_can_send()
2021-06-13 22:11:29,074  18.216.200.111 ConnectedRemotePeer.handle_receive_data()
2021-06-13 22:11:29,074  18.216.200.111 ConnectedRemotePeer.handle_message_received(GetBlocksMessage ts: 2021-06-13T22:11:29-07:00, id: 0000000139, req: 0000000137, ctx: 08814615144814270758)
2021-06-13 22:11:29,074  18.216.200.111 ConnectedRemotePeer.handle_get_blocks_message_received()
2021-06-13 22:11:29,074  18.216.200.111 requested start_height=24501
2021-06-13 22:11:29,091  18.216.200.111 ConnectedRemotePeer.send_message(InventoryMessage ts: 2021-06-13T22:11:29-07:00, id: 0000000140, req: 0000000139, ctx: 08814615144814270758)
2021-06-13 22:11:29,091 ConnectedRemotePeer.handle_can_send()
```
The line `requested start_height=` is something I added, in the commit linked above.

What I find strange about this:
- The peer at 24.194.193.244 (not mine) keeps asking for block 5501 - why? 
- The peer at 18.216.200.111 is mine (on a different machine). It's been running for over 24 hours and has a chain height of 87000+. Why is it asking for blocks at height 24000-25000 right now?

**Comment by lk16** [comment] 2021-06-14 06:41
Strange. Did you notice that all those requested start_heights are a multiple of 500 plus one?

**Comment by atramos** [comment] 2021-06-14 14:14
> Strange. Did you notice that all those requested start_heights are a multiple of 500 plus one?

Yes, the multiple of 500 aspect is normal, as it matches maximum download size in networking params.py

**Comment by atramos** [comment] 2021-06-27 19:25
Actually not sure this is a bug, as everything seems to be working normally.

**Comment by atramos** [comment] 2021-06-27 19:26
@sashimi-houdini any thoughts on this?

**Comment by sashimi-houdini** [comment] 2022-08-05 21:47
I'm closing this as "too hard to reproduce right now". If we ever get re-occurrences we can always re-open.

**Closed by sashimi-houdini** 2022-08-05 21:47 UTC
Labels: question
