### ISSUE TITLE
forks!

### ISSUE THREAD

**Issue by refacktor** [skepticoin/skepticoin#122] opened 2022-06-04 16:57 UTC
The blockchain keeps forking, way more than it used to.

In the logs, this shows up as `Diverges at N blocks`

**Comment by atramos** [comment] 2022-06-04 22:50
Fixed now, just making note of root cause... as the blockchain got larger, it took longer and longer to write it to disk. The fix is to broadcast blocks before saving to disk (just making the disk writes faster could have fixed it too).

**Comment by atramos** [comment] 2022-06-08 02:42
@sashimi-houdini please consider merging and releasing PR #120 as soon as possible due to this issue. After additional logging, I see unpatched nodes taking up to 30 seconds to broadcast their mined blocks. That'll cause 25% of blocks to fork, and it'll get worse as the blockchain grows larger.

**Closed** 2022-08-06 14:34 UTC
Labels: bug, scalability
