### ISSUE TITLE
Bad Peer 127.0.0.1

### ISSUE THREAD

**Issue by lk16** [skepticoin/skepticoin#84] opened 2021-06-16 13:38 UTC
I run 4 miners and got this after a few hours of mining. 
Should we hardcode to not connect to ourselves?

```
Bad Peer (disconnected without hello): 127.0.0.1                                                                                                               
Bad Peer (disconnected without hello): 127.0.0.1                                                                                                               
Bad Peer (disconnected without hello): 127.0.0.1                                                                                                               
Bad Peer (disconnected without hello): 127.0.0.1 
```

**Comment by atramos** [comment] 2021-06-16 14:11
I'd like to find out why it's even trying, and fix the root cause instead if possible.

**Comment by atramos** [comment] 2021-06-26 22:00
I think this might be caused by one of the unit tests, which is invoked in the git commit-hook, connecting to the "production" skepticoin peer network and broadcasting the "127.0.0.1".

**Comment by atramos** [comment] 2021-06-27 19:05
related: #54

**Comment by atramos** [comment] 2021-06-27 19:05
The fix for this is going to be tricky, because a simple fix breaks the tests.

**Comment by atramos** [comment] 2021-06-28 01:57
Actually, not so tricky. Ultimately this was caused by removing the peers.json update out of DiskInterface.

**Comment by sashimi-houdini** [comment] 2022-08-05 21:44
Closed this to reflect my understanding of @refacktor's remark above

**Closed** 2022-08-05 21:44 UTC
Labels: technical debt
