### ISSUE TITLE
INVALID transaction input's output_reference does not exist as an unspent out

### ISSUE THREAD

**Issue by atramos** [skepticoin/skepticoin#53] opened 2021-06-01 15:12 UTC
Error seen at 2021-06-01T11:58:19.364Z

**Comment by sashimi-houdini** [comment] 2021-06-02 19:08
https://github.com/skepticoin/skepticoin/issues/18#issuecomment-837101185 deals with this

In short: the client is currently verbose when receiving invalid transactions. This is by design. It may be that some part of our own tooling accidentally sends invalid transactions. However, the nature of peer to peer networks make it hard to debug this from the receiving side.

Closing this issue for now.

**Closed by sashimi-houdini** 2021-06-02 19:08 UTC
